name: sns_deepfake
description: "DeepFake Social Network"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.1 <4.0.0"

dependencies:
    animations: ^2.0.11
    cached_network_image: ^3.3.1
    connectivity_plus: ^6.0.2
    cupertino_icons: ^1.0.6
    dartz: ^0.10.1
    device_info_plus: ^10.0.1
    dio: ^5.4.1
    dio_smart_retry: ^6.0.0
    easy_localization: ^3.0.5
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.4
    flutter_dotenv: ^5.1.0
    flutter_flavor: ^3.1.3
    flutter_local_notifications: ^17.0.0
    flutter_native_splash: ^2.4.0
    flutter_screenutil: ^5.9.0
    font_awesome_flutter: ^10.7.0
    get_it: ^7.6.7
    go_router: ^13.2.1
    http_parser: ^4.0.2
    image_cropper: ^5.0.1
    image_picker: ^1.1.0
    intl: ^0.18.1
    logger: ^2.1.0
    lottie: ^3.1.0
    permission_handler: ^11.3.0
    shared_preferences: ^2.2.2
    shimmer: ^3.0.0
    toastification: ^1.2.1
    url_launcher: ^6.2.5

dev_dependencies:
    change_app_package_name: ^1.1.0 # change bundle or (package name) + directory For Android
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter
    # app/build.gradle - android - namespace: có thể chưa đổi
    rename: ^3.0.2 # Change appName + bundle or (package name) For both iOS and Android

# https://icon.kitchen
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/app/icon_transparent.png"
    adaptive_icon_background: "#ffffff"
    # adaptive_icon_foreground: "assets/app/"

flutter_native_splash:
    color: "#F5FCF9"
    color_dark: "#1D1D35"
    image: "assets/app/icon_transparent.png"
    image_dark: "assets/app/icon_transparent.png"

    android_12:
        color: "#F5FCF9"
        color_dark: "#1D1D35"
        image: "assets/app/icon_transparent.png"
        image_dark: "assets/app/icon_transparent.png"

    web: false

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/app/
        - assets/images/
        - assets/lotties/
        - assets/translations/

    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat-Light.ttf
                weight: 300
              - asset: assets/fonts/Montserrat-Medium.ttf
                weight: 500
              - asset: assets/fonts/Montserrat-Regular.ttf
                weight: 400
              - asset: assets/fonts/Montserrat-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Montserrat-Black.ttf
                weight: 700
              - asset: assets/fonts/Montserrat-Bold.ttf
                weight: 800
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Light.ttf
                weight: 300
              - asset: assets/fonts/Poppins-Regular.ttf
                weight: 400
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-MediumItalic.ttf
                weight: 500
                style: italic
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Black.ttf
                weight: 700
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 800
