#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run husky hook in server
if git diff --name-only --cached | grep 'server/';
then
    cd server
    yarn sync
    yarn lint-staged
    cd ..
fi

# Run husky hook in admin
if git diff --name-only --cached | grep 'admin/';
then
    cd admin
    yarn sync
    yarn lint-staged
    cd ..
fi